config/routes.rb
Rails.application.routes.draw do

  resources :quotes do
    resources :comments
  end

  root 'quotes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :quote

  # TODO display errors msg for this validation
  validates :nick, presence: true, length: { minimum: 3, maximum: 25 }
end

app/models/quote.rb
class Quote < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :content, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "admin", password: "admin", only: :destroy
  
  def create
    @quote = Quote.find(params[:quote_id])
    @comment = @quote.comments.create(comment_params)
    redirect_to quote_path(@quote)
  end

  def destroy
    @quote = Quote.find(params[:quote_id])
    @comment = @quote.comments.find(params[:id])
    @comment.destroy
    redirect_to quote_path(@quote)
  end

  private def comment_params
    params.require(:comment).permit(:nick, :body)
  end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]

  def index
    @quotes = Quote.readonly.all
  end

  def show
    @quote = Quote.readonly.find(params[:id])
  end

  def new
    @quote = Quote.new
  end

  def edit
    @quote = Quote.find(params[:id])
  end

  def create
    @quote = Quote.new(quote_params)

    if @quote.save
      redirect_to quotes_path
    else
      render 'new'
    end
  end

  def update
    @quote = Quote.find(params[:id])

    if @quote.update(quote_params)
      redirect_to quotes_path
    else
      render 'edit'
    end
  end

  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy

    redirect_to quotes_path
  end

  private def quote_params
    params.require(:quote).permit(:content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/comments/_comment.html.erb
</br>


<div class="row">
  <div class="col-2">
    <i><strong><%= comment.nick %> </strong></i>
  </div>
  <div class="col-6">
    <%= comment.body %>
  </div>
  <div class="col-2">
    <%= link_to 'Delete', [comment.quote, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  </div>
</div>


</br>

app/views/comments/_form.html.erb
<%= bootstrap_form_with(model: [@quote, @quote.comments.build ], local: true) do |f| %>

  <p>Nick should have min 3 and max 25 characters.</p>
  <%= f.text_field :nick %>
  <%= f.text_area :body %>

  <%= f.primary "Save" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CollegeNetguru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="<%= quotes_path %>">Anonymous Quotes</a>
      <form class="form-inline">
        <%= link_to "Add new quote", new_quote_path, class: 'btn btn-outline-success' %>
      </form>
    </nav>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/quotes/_form.html.erb
<%= bootstrap_form_with(model: @quote, local: true) do |f| %>

  <%= f.text_area :content %>

  <%= f.primary "Save" %>

<% end %>

</br>

app/views/quotes/edit.html.erb
</br></br>
<%= link_to "Return", quote_path(@quote), class: "btn btn-secondary" %>
</br></br>

<h1>Edit quote</h1>

<%= render 'form' %>

app/views/quotes/index.html.erb
<% @quotes.each do |quote| %>

  <a id='link-show' href="<%= quote_path(quote) %>">

    <div id="fancy-quote" class="effect">
      <blockquote><%= quote.content %></blockquote>
      <cite>Anonymous</cite>
    </div>

  </a>

<% end %>

app/views/quotes/new.html.erb
</br></br>
<%= link_to "Return", quotes_path, class: "btn btn-secondary" %>
</br></br>

<h1>Add new one</h1>

<%= render 'form' %>

app/views/quotes/show.html.erb
<div id="fancy-quote">
  <blockquote><%= @quote.content %></blockquote>
  <cite>Anonymous</cite>
</div>


<div class="row">
  <div class="col-sm">
    <%= link_to "Return", quotes_path, class: 'btn btn-outline-secondary' %>
    <%= link_to "Edit", edit_quote_path(@quote), class: 'btn btn-outline-primary' %>
    <%= link_to "Delete", quote_path(@quote), class: 'btn btn-outline-danger', method: :delete, data: { confirm: 'Are you sure?'} %>
  </div>
  <div class="col-sm">
    <i>Last updated: <%= @quote.updated_at %></i>
  </div>
</div>

</br></br>

<h4>Add comment</h4>
<i><%= render 'comments/form' %></i>

</br></br>

<h4>Comments</h4>
<%= render @quote.comments.select(&:persisted?) %>